"""Binance 行情 REST 方法集合（mixin）。

从 request_base.py 拆分，供 BinanceRequestData 混入。
"""

from __future__ import annotations

from bt_api_base.functions.calculate_time import datetime2timestamp
from bt_api_base.functions.utils import update_extra_data


class RestMarketMixin:
    """行情 REST 方法集合。"""

    def _get_tick(self, symbol, extra_data=None, **kwargs):
        """Get tick price by symbol
        :param symbol: default None, get all the currency, can be string, e.g. "BTC-USDT".
        :param extra_data: extra_data, default is None, can be a dict passed by user
        :param kwargs: pass key-worded, variable-length arguments.
        :return: RequestData.
        """
        request_type = "get_tick"
        path = self._params.get_rest_path(request_type)
        if symbol is not None:
            request_symbol = self._params.get_symbol(symbol)
            params = {
                "symbol": request_symbol,
            }
        else:
            params: dict[str, Any] = {}
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_tick_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_depth(self, symbol, size=20, extra_data=None, **kwargs):
        """Get depth data from okx using requests package
        :param symbol: instrument name
        :param size: the size of the orderbook level
        :param args:  pass a variable number of arguments to a function.
        :param extra_data: extra_data, generated by user and extended by function
        :param kwargs: pass key-worded, variable-length arguments.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_depth"
        request_symbol = self._params.get_symbol(symbol)
        params = {"symbol": request_symbol, "limit": size}
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_depth_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_kline(
        self, symbol, period, count=100, start_time=None, end_time=None, extra_data=None, **kwargs
    ):
        """Get kline from okx using request.
        :param symbol: instrument name.
        :param period: kline interval.
        :param count: kline number, default is 100.
        :param start_time: start_time
        :param end_time: end_time
        :param extra_data: extra_data, generated by user and function
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_kline"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "interval": self._params.get_period(period),
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
                params.update({"startTime": start_time})
            elif isinstance(start_time, int):
                params.update({"startTime": start_time})
            else:
                self.logger.error("start_time is not str or int")
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
                params.update({"endTime": end_time})
            elif isinstance(end_time, int):
                params.update({"endTime": end_time})
            else:
                self.logger.error("end_time is not str or int")
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_kline_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_funding_rate(self, symbol, extra_data=None, **kwargs):
        """Get funding rate from okx
        :param symbol: symbol name, eg: BTC-USDT.
        :param args:  pass a variable number of arguments to a function.
        :param extra_data: extra_data, generated by user and function
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_funding_rate"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
        }
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_funding_rate_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_history_funding_rate(
        self, symbol, start_time, end_time, count=1000, extra_data=None, **kwargs
    ):
        """Get funding rate from binance
        :param symbol: symbol name, eg: BTC-USDT.
        :param start_time: start time
        :param end_time: end time
        :param count: count
        :param args:  passes a variable number of arguments to a function.
        :param extra_data: extra_data, generated by user and function
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_history_funding_rate"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "limit": count,
        }
        if isinstance(start_time, str):
            start_time = int(datetime2timestamp(start_time) * 1000)
            # print("start_time = ", start_time)
            params.update({"startTime": start_time})
        elif isinstance(start_time, int):
            params.update({"startTime": start_time})
        else: pass
        if isinstance(end_time, str):
            end_time = int(datetime2timestamp(end_time) * 1000)
            # print("end_time = ", end_time)
            params.update({"endTime": end_time})
        elif isinstance(start_time, int):
            params.update({"endTime": end_time})
        else: pass

        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_history_funding_rate_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_mark_price(self, symbol, extra_data=None, **kwargs):
        """Get mark_price from okx
        :param symbol: symbol name, eg: BTC-USDT.
        :param extra_data: extra_data, generated by user and function
        :param args:  pass a variable number of arguments to a function.
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_mark_price"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
        }
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": "SPOT",
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_mark_price_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data













    def get_tick(self, symbol, extra_data=None, **kwargs):
        """get_tick method"""
        path, params, extra_data = self._get_tick(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_depth(self, symbol: Any, count: Any = 20, extra_data: Any = None, **kwargs: Any) -> Any:
        """get_depth method"""
        path, params, extra_data = self._get_depth(symbol, count, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_kline(
        self,
        symbol: Any,
        period: Any,
        count: Any = 100,
        start_time: Any = None,
        end_time: Any = None,
        extra_data: Any = None,
        **kwargs: Any,
    ) -> Any:
        """get_kline method"""
        path, params, extra_data = self._get_kline(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_funding_rate(self, symbol, extra_data=None, **kwargs):
        """get_funding_rate method"""
        path, params, extra_data = self._get_funding_rate(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data)
        return data


    def get_history_funding_rate(
        self, symbol, start_time=None, end_time=None, count=1000, extra_data=None, **kwargs
    ):
        """get_history_funding_rate method"""
        path, params, extra_data = self._get_history_funding_rate(
            symbol, start_time, end_time, count, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data)
        return data


    def get_mark_price(self, symbol, extra_data=None, **kwargs):
        """get_mark_price method"""
        path, params, extra_data = self._get_mark_price(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data)
        return data













    def get_clear_price(self, symbol, extra_data=None, **kwargs):
        """get_clear_price method"""
        pass

