"""Binance 行情 REST 方法集合（mixin）。

从 request_base.py 拆分，供 BinanceRequestData 混入。
"""

from __future__ import annotations

from bt_api_base.functions.calculate_time import datetime2timestamp
from bt_api_base.functions.utils import update_extra_data


class RestMarketMixin:
    """行情 REST 方法集合。"""

    def _get_tick(self, symbol, extra_data=None, **kwargs):
        """Get tick price by symbol
        :param symbol: default None, get all the currency, can be string, e.g. "BTC-USDT".
        :param extra_data: extra_data, default is None, can be a dict passed by user
        :param kwargs: pass key-worded, variable-length arguments.
        :return: RequestData.
        """
        request_type = "get_tick"
        path = self._params.get_rest_path(request_type)
        if symbol is not None:
            request_symbol = self._params.get_symbol(symbol)
            params = {
                "symbol": request_symbol,
            }
        else:
            params: dict[str, Any] = {}
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_tick_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_depth(self, symbol, size=20, extra_data=None, **kwargs):
        """Get depth data from okx using requests package
        :param symbol: instrument name
        :param size: the size of the orderbook level
        :param args:  pass a variable number of arguments to a function.
        :param extra_data: extra_data, generated by user and extended by function
        :param kwargs: pass key-worded, variable-length arguments.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_depth"
        request_symbol = self._params.get_symbol(symbol)
        params = {"symbol": request_symbol, "limit": size}
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_depth_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_kline(
        self, symbol, period, count=100, start_time=None, end_time=None, extra_data=None, **kwargs
    ):
        """Get kline from okx using request.
        :param symbol: instrument name.
        :param period: kline interval.
        :param count: kline number, default is 100.
        :param start_time: start_time
        :param end_time: end_time
        :param extra_data: extra_data, generated by user and function
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_kline"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "interval": self._params.get_period(period),
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
                params.update({"startTime": start_time})
            elif isinstance(start_time, int):
                params.update({"startTime": start_time})
            else:
                self.logger.error("start_time is not str or int")
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
                params.update({"endTime": end_time})
            elif isinstance(end_time, int):
                params.update({"endTime": end_time})
            else:
                self.logger.error("end_time is not str or int")
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_kline_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_funding_rate(self, symbol, extra_data=None, **kwargs):
        """Get funding rate from okx
        :param symbol: symbol name, eg: BTC-USDT.
        :param args:  pass a variable number of arguments to a function.
        :param extra_data: extra_data, generated by user and function
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_funding_rate"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
        }
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_funding_rate_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_history_funding_rate(
        self, symbol, start_time, end_time, count=1000, extra_data=None, **kwargs
    ):
        """Get funding rate from binance
        :param symbol: symbol name, eg: BTC-USDT.
        :param start_time: start time
        :param end_time: end time
        :param count: count
        :param args:  passes a variable number of arguments to a function.
        :param extra_data: extra_data, generated by user and function
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_history_funding_rate"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "limit": count,
        }
        if isinstance(start_time, str):
            start_time = int(datetime2timestamp(start_time) * 1000)
            # print("start_time = ", start_time)
            params.update({"startTime": start_time})
        elif isinstance(start_time, int):
            params.update({"startTime": start_time})
        else: pass
        if isinstance(end_time, str):
            end_time = int(datetime2timestamp(end_time) * 1000)
            # print("end_time = ", end_time)
            params.update({"endTime": end_time})
        elif isinstance(start_time, int):
            params.update({"endTime": end_time})
        else: pass

        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_history_funding_rate_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_mark_price(self, symbol, extra_data=None, **kwargs):
        """Get mark_price from okx
        :param symbol: symbol name, eg: BTC-USDT.
        :param extra_data: extra_data, generated by user and function
        :param args:  pass a variable number of arguments to a function.
        :param kwargs: pass a key-worded, variable-length argument list.
        :return: tuple of (str, dict, dict).
        """
        request_type = "get_mark_price"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
        }
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": "SPOT",
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_mark_price_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_open_interest(self, symbol, extra_data=None, **kwargs):
        request_type = "get_open_interest"
        request_symbol = self._params.get_symbol(symbol)
        params = {"symbol": request_symbol}
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_agg_trades(
        self,
        symbol,
        from_id=None,
        start_time=None,
        end_time=None,
        count=500,
        extra_data=None,
        **kwargs,
    ):
        request_type = "get_agg_trades"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "limit": count,
        }
        if from_id is not None:
            params["fromId"] = from_id
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_continuous_kline(
        self,
        pair,
        period,
        contract_type="PERPETUAL",
        count=100,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        request_type = "get_continuous_kline"
        params = {
            "pair": self._params.get_symbol(pair),
            "contractType": contract_type,
            "interval": self._params.get_period(period),
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": pair,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": self._get_kline_normalize_function,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_index_price_kline(
        self, pair, period, count=100, start_time=None, end_time=None, extra_data=None, **kwargs
    ):
        request_type = "get_index_price_kline"
        params = {
            "pair": self._params.get_symbol(pair),
            "interval": self._params.get_period(period),
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": pair,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_mark_price_kline(
        self, symbol, period, count=100, start_time=None, end_time=None, extra_data=None, **kwargs
    ):
        request_type = "get_mark_price_kline"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "interval": self._params.get_period(period),
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_funding_info(self, extra_data=None, **kwargs):
        request_type = "get_funding_info"
        params: dict[str, Any] = {}
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": "ALL",
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_long_short_ratio(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        request_type = "get_long_short_ratio"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "period": period,
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_taker_buy_sell_volume(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        request_type = "get_taker_buy_sell_volume"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "period": period,
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_top_long_short_account_ratio(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """ ().

        Args: symbol:
            period:  (5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d)
            count:  (1-500)
            start_time: 
            end_time: 
            extra_data: 
            **kwargs: 

        Returns: tuple: (path, params, extra_data)

        """
        request_type = "get_top_long_short_account_ratio"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "period": period,
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_top_long_short_position_ratio(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """ ().

        Args: symbol:
            period:  (5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d)
            count:  (1-500)
            start_time: 
            end_time: 
            extra_data: 
            **kwargs: 

        Returns: tuple: (path, params, extra_data)

        """
        request_type = "get_top_long_short_position_ratio"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "period": period,
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_open_interest_hist(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """.

        Args: symbol:
            period:  (5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 1d)
            count:  (1-500)
            start_time: 
            end_time: 
            extra_data: 
            **kwargs: 

        Returns: tuple: (path, params, extra_data)

        """
        request_type = "get_open_interest_hist"
        request_symbol = self._params.get_symbol(symbol)
        params = {
            "symbol": request_symbol,
            "period": period,
            "limit": count,
        }
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol,
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def _get_force_orders(
        self, symbol=None, start_time=None, end_time=None, limit=None, extra_data=None, **kwargs
    ):
        """.

        Args: symbol:  ()
            start_time: 
            end_time: 
            limit:  (1-100)
            extra_data: 
            **kwargs: 

        Returns: tuple: (path, params, extra_data)

        """
        request_type = "get_force_orders"
        params: dict[str, Any] = {}
        if symbol is not None:
            request_symbol = self._params.get_symbol(symbol)
            params["symbol"] = request_symbol
        if start_time is not None:
            if isinstance(start_time, str):
                start_time = int(datetime2timestamp(start_time) * 1000)
            params["startTime"] = start_time
        if end_time is not None:
            if isinstance(end_time, str):
                end_time = int(datetime2timestamp(end_time) * 1000)
            params["endTime"] = end_time
        if limit is not None:
            params["limit"] = limit
        path = self._params.get_rest_path(request_type)
        extra_data = update_extra_data(
            extra_data,
            **{
                "request_type": request_type,
                "symbol_name": symbol or "ALL",
                "asset_type": self.asset_type,
                "exchange_name": self.exchange_name,
                "normalize_function": None,
            },
        )
        if kwargs is not None:
            extra_data.update(kwargs)
        return path, params, extra_data

    def get_tick(self, symbol, extra_data=None, **kwargs):
        """get_tick method"""
        path, params, extra_data = self._get_tick(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_depth(self, symbol: Any, count: Any = 20, extra_data: Any = None, **kwargs: Any) -> Any:
        """get_depth method"""
        path, params, extra_data = self._get_depth(symbol, count, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_kline(
        self,
        symbol: Any,
        period: Any,
        count: Any = 100,
        start_time: Any = None,
        end_time: Any = None,
        extra_data: Any = None,
        **kwargs: Any,
    ) -> Any:
        """get_kline method"""
        path, params, extra_data = self._get_kline(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_funding_rate(self, symbol, extra_data=None, **kwargs):
        """get_funding_rate method"""
        path, params, extra_data = self._get_funding_rate(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data)
        return data


    def get_history_funding_rate(
        self, symbol, start_time=None, end_time=None, count=1000, extra_data=None, **kwargs
    ):
        """get_history_funding_rate method"""
        path, params, extra_data = self._get_history_funding_rate(
            symbol, start_time, end_time, count, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data)
        return data


    def get_mark_price(self, symbol, extra_data=None, **kwargs):
        """get_mark_price method"""
        path, params, extra_data = self._get_mark_price(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data)
        return data

    def get_open_interest(self, symbol, extra_data=None, **kwargs):
        """get_open_interest method"""
        path, params, extra_data = self._get_open_interest(symbol, extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_agg_trades(
        self,
        symbol,
        from_id=None,
        start_time=None,
        end_time=None,
        count=500,
        extra_data=None,
        **kwargs,
    ):
        """get_agg_trades method"""
        path, params, extra_data = self._get_agg_trades(
            symbol, from_id, start_time, end_time, count, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data



    def get_continuous_kline(
        self,
        pair,
        period,
        contract_type="PERPETUAL",
        count=100,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """get_continuous_kline method"""
        path, params, extra_data = self._get_continuous_kline(
            pair, period, contract_type, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_index_price_kline(
        self, pair, period, count=100, start_time=None, end_time=None, extra_data=None, **kwargs
    ):
        """get_index_price_kline method"""
        path, params, extra_data = self._get_index_price_kline(
            pair, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_mark_price_kline(
        self, symbol, period, count=100, start_time=None, end_time=None, extra_data=None, **kwargs
    ):
        """get_mark_price_kline method"""
        path, params, extra_data = self._get_mark_price_kline(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_funding_info(self, extra_data=None, **kwargs):
        """get_funding_info method"""
        path, params, extra_data = self._get_funding_info(extra_data, **kwargs)
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_long_short_ratio(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """get_long_short_ratio method"""
        path, params, extra_data = self._get_long_short_ratio(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_taker_buy_sell_volume(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """get_taker_buy_sell_volume method"""
        path, params, extra_data = self._get_taker_buy_sell_volume(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data

    def get_top_long_short_account_ratio(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """ ()."""
        path, params, extra_data = self._get_top_long_short_account_ratio(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_top_long_short_position_ratio(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """ ()."""
        path, params, extra_data = self._get_top_long_short_position_ratio(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data


    def get_open_interest_hist(
        self,
        symbol,
        period="5m",
        count=30,
        start_time=None,
        end_time=None,
        extra_data=None,
        **kwargs,
    ):
        """."""
        path, params, extra_data = self._get_open_interest_hist(
            symbol, period, count, start_time, end_time, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=False)
        return data

    # NOTE: get_liquidation_orders endpoint (/fapi/v1/allForceOrder) discontinued by Binance
    # Use WebSocket stream !forceOrder@arr for liquidation data instead


    def get_force_orders(
        self, symbol=None, start_time=None, end_time=None, limit=None, extra_data=None, **kwargs
    ):
        """."""
        path, params, extra_data = self._get_force_orders(
            symbol, start_time, end_time, limit, extra_data, **kwargs
        )
        data = self.request(path, params=params, extra_data=extra_data, is_sign=True)
        return data

    # NOTE: get_open_interest_interval endpoint not available
    # Use get_open_interest_hist for historical open interest data instead

    async def async_request(
        self, path, params=None, body=None, extra_data=None, timeout=10, is_sign=False
    ):
        """Http request function
        Args: path (TYPE): request url
            params (dict, optional): in url
            body (dict, optional): in request body
            timeout (int, optional): request timeout(s)
            extra_data(dict,None): extra_data, generate by user
            is_sign (bool, optional): whether to signature.
        """
        if params is None:
            params: dict[str, Any] = {}
        if extra_data is None:
            extra_data = {}
        # if body is None:
        #     body = {}
        method, path = path.split(" ", 1)
        if is_sign is False:
            req = params
        else:
            req = {
                "recvWindow": 3000,
                "timestamp": int(time.time() * 1000),
            }
            req.update(params)
            sign = urlencode(req)
            req["signature"] = self.sign(sign)
        req = urlencode(req)
        url = f"{self._params.rest_url}{path}?{req}"
        headers = {
            "X-MBX-APIKEY": self.public_key,
        }
        res = await self.async_http_request(method, url, headers, body, timeout)
        self._raise_if_error(res)
        # self.request_logger.info(f"""request:{get_string_tz_time()} {res}""")
        # request_type = extra_data.get('request_type')
        # data_factory = self._params.request_data_dict.get(request_type)
        return RequestData(res, extra_data)

    # noinspection PyBroadException




    def get_clear_price(self, symbol, extra_data=None, **kwargs):
        """get_clear_price method"""
        pass

